topkalaMag/urls.py
from django.urls import path
from . import views

app_name = 'topkalaMag'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('search-results/', views.SearchResultsView.as_view(), name='search-results'),
    path('single-post/<int:pk>/', views.SinglePostView.as_view(), name='single-post'),
    path('error404/', views.Error404View.as_view(), name='error404'),


]

topkalaTemplate/urls.py
from django.urls import path
from . import views

app_name = 'topkalaTemplate'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product/<int:product_id>/', views.SingleProductView.as_view(), name='single-product'),
    path('product/<int:product_id>/add_comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('product/<int:product_id>/send-email/', views.send_product_email, name='send_product_email'),
    path('product/sent-success/', views.ProductSentSuccessView.as_view(), name='product_sent_success'),
    path('product/sent-fail/', views.ProductSentFailView.as_view(), name='product_sent_fail'),
    # path('product/<int:product_id>/add_to_favorite/', views.AddToFavoriteView.as_view(), name='add_to_favorite'),
    path('add_to_favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart-empty/', views.CartEmptyView.as_view(), name='cart-empty'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('404/', views.PageNotFoundView.as_view(), name='404'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password-change'),
    path('profile-additional-info/', views.ProfileAdditionalInfoView.as_view(), name='profile-additional-info'),
    path('profile-favorites/', views.ProfileFavoritesView.as_view(), name='profile-favorites'),
    path('profile-orders-return/', views.ProfileOrdersReturnView.as_view(), name='profile-orders-return'),
    path('profile-personal-info/', views.ProfilePersonalInfoView.as_view(), name='profile-personal-info'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('search-amazing/', views.SearchAmazingView.as_view(), name='search-amazing'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('shopping-complete-buy/', views.ShoppingCompleteBuyView.as_view(), name='shopping-complete-buy'),
    path('shopping-no-complete-buy/', views.ShoppingNoCompleteBuyView.as_view(), name='shopping-no-complete-buy'),
    path('shopping-payment/', views.ShoppingPaymentView.as_view(), name='shopping-payment'),
    path('shopping/', views.ShoppingView.as_view(), name='shopping'),
    path('welcome/', views.WelcomeView.as_view(), name='welcome'),
]

topkalaTemplate/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.urls import reverse





class Brand(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان برند')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'برند'
        verbose_name_plural = 'برندها'




def special_brand_image_path(instance, filename):
    date_str = datetime.now().strftime('%Y/%m/%d')
    unique_filename = f'topkalaTemplate/special_brand_images/{date_str}/{filename}'
    return unique_filename


class SpecialBrand(models.Model):
    name = models.CharField(max_length=255, verbose_name='نام برند')
    logo = models.ImageField(upload_to=special_brand_image_path, verbose_name='لوگو برند')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'برند ویژه'
        verbose_name_plural = 'برندهای ویژه'


class Category(models.Model):
    title = models.CharField(max_length=255)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    url = models.URLField(blank=True ,null=True)

    def __str__(self):
        return self.title



def product_image_path(instance, filename):
    date_str = datetime.now().strftime('%Y/%m/%d')
    unique_filename = f'topkalaTemplate/product_images/{date_str}/{filename}'
    return unique_filename


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان محصول')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='دسته‌بندی')
    # image = models.ImageField(upload_to=product_image_path, verbose_name='تصویر محصول')
    old_price = models.IntegerField(verbose_name='قیمت قبلی')
    new_price = models.IntegerField(verbose_name='قیمت جدید')
    discount_percent = models.PositiveIntegerField(verbose_name='درصد تخفیف')
    description = models.TextField(verbose_name='توضیحات محصول')
    countdown_date = models.DateTimeField(null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='برند',null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'
    
    def get_absolute_url(self):
        # ایجاد URL محصول
        return reverse('topkalaTemplate:single-product', args=[str(self.id)])

    def get_twitter_share_url(self):
        # تابع برای ایجاد لینک اشتراک‌گذاری در توییتر
        product_url = self.get_absolute_url()
        twitter_share_url = f'https://twitter.com/intent/tweet?url={product_url}&text={self.title}'
        return twitter_share_url

    def get_facebook_share_url(self):
        # تابع برای ایجاد لینک اشتراک‌گذاری در فیسبوک
        product_url = self.get_absolute_url()
        facebook_share_url = f'https://www.facebook.com/sharer/sharer.php?u={product_url}'
        return facebook_share_url

    def get_google_plus_share_url(self):
        # تابع برای ایجاد لینک اشتراک‌گذاری در گوگل پلاس
        product_url = self.get_absolute_url()
        google_plus_share_url = f'https://plus.google.com/share?url={product_url}'
        return google_plus_share_url
    



class FavoriteProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'product')


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE, verbose_name='محصول')
    image = models.ImageField(upload_to=product_image_path, verbose_name='تصویر محصول')

    def __str__(self):
        return self.product.title + ' - Image'

    class Meta:
        verbose_name = 'تصویر محصول'
        verbose_name_plural = 'تصاویر محصولات'



def slider_image_path(instance, filename):
    date_str = datetime.now().strftime('%Y/%m/%d')
    unique_filename = f'topkalaTemplate/slider_images/{date_str}/{filename}'
    return unique_filename



class SliderImage(models.Model):
    image = models.ImageField(upload_to=slider_image_path)

    def __str__(self):
        return self.image.name


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE) 
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

topkalaTemplate/forms.py
from django import forms

class EmailProductLinkForm(forms.Form):
    to_email = forms.EmailField(label='آدرس ایمیل مخاطب', required=True)

topkalaTemplate/views.py
from django.views.generic import View
from .models import *
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import EmailProductLinkForm
from django.core.mail import send_mail
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import HttpResponse




class AddCommentView(View):
    # @login_required
    def post(self, request, product_id):
        product = Product.objects.get(pk=product_id)
        print("aaaaaaaaaaaaa",request.user)
        author = request.user
        text = request.POST['text']
        parent_comment_id = request.POST.get('parent_comment_id')  # دریافت شناسه نظر والد اگر وجود داشته باشد
        if parent_comment_id:
            parent_comment = Comment.objects.get(pk=parent_comment_id)
            Comment.objects.create(product=product, author=author, text=text, parent_comment=parent_comment)
        else:
            Comment.objects.create(product=product, author=author, text=text)
            
        return redirect('topkalaTemplate:single-product', product_id=product_id)




class ProductSentSuccessView(View):
    def get(self, request):
        return HttpResponse('ارسال محصول موفقیت‌آمیز بود!')


class ProductSentFailView(View):
    def get(self, request):
        return HttpResponse('ارسال محصول ناموفق بود!')



def send_product_email(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        email_form = EmailProductLinkForm(request.POST)
        if email_form.is_valid():
            to_email = email_form.cleaned_data['to_email']
            
            # ایجاد لینک محصول
            product_url = request.build_absolute_uri(product.get_absolute_url())

            # ارسال ایمیل
            subject = f'لینک محصول: {product.title}'
            message = f'لینک محصول: {product_url}'
            from_email = settings.DEFAULT_FROM_EMAIL
            recipient_list = [to_email]
            
            send_mail(subject, message, from_email, recipient_list)
            
            # موفقیت‌آمیز بودن ارسال ایمیل را به کاربر نمایش دهید
            return redirect('topkalaTemplate:product_sent_success')
    
    # در صورتی که ارسال ایمیل موفقیت‌آمیز نبود
    return redirect('topkalaTemplate:product_sent_fail')




# @login_required  # تأكید می‌کند که کاربر وارد شده باشد.
def add_to_favorites(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        favorite, created = FavoriteProduct.objects.get_or_create(user=request.user, product=product)
        if created:
            return JsonResponse({'status': 'added'})
        else:
            return JsonResponse({'status': 'already_added'})
    except Product.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'محصول مورد نظر یافت نشد'})



class SingleProductView(View):
    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)

        categories = []

        categories.append(product.category)

        parent_category = product.category.parent
        while parent_category:
            categories.append(parent_category)
            parent_category = parent_category.parent

        email_form = EmailProductLinkForm()

        brand = product.brand 

        comments = Comment.objects.filter(product=product)
        
        context = {
            'product': product,
            'categories': reversed(categories), 
            'email_form': email_form,
            'brand': brand,
            'comments': comments,
        }

        return render(request, 'topkalaTemplate/single-product.html', context)




class IndexView(View):
    def get(self, request):
        slider_images = SliderImage.objects.all()
        products = Product.objects.filter(
            Q(category__title="شگفت‌انگیزها") | Q(category__parent__title="شگفت‌انگیزها")
        )
        category1 = Category.objects.get(title='kkkk')
        category2 = Category.objects.get(title='کالای دیجیتال')

        products_category1 = Product.objects.filter(category=category1)
        products_category2 = Product.objects.filter(category=category2)

        special_brands = SpecialBrand.objects.all()

        recent_discounted_products = Product.objects.filter(discount_percent__gt=0).order_by('-id')[:4]

        context = {
            'products': products,
            'slider_images': slider_images,
            'category1':category1,
            'category2':category2,
            'products_category1': products_category1,
            'products_category2': products_category2,
            'special_brands': special_brands,
            'recent_discounted_products': recent_discounted_products,

        }

        return render(request, 'topkalaTemplate/index.html', context)





class AboutView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/about.html', {})

class CartView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/cart.html', {})

class CartEmptyView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/cart-empty.html', {})

class CheckoutView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/checkout.html', {})

class PageNotFoundView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/404.html', {})

class LoginView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/login.html', {})

class PasswordChangeView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/password-change.html', {})

class ProfileAdditionalInfoView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/profile-additional-info.html', {})

class ProfileFavoritesView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/profile-favorites.html', {})

class ProfileOrdersReturnView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/profile-orders-return.html', {})

class ProfilePersonalInfoView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/profile-personal-info.html', {})

class ProfileView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/profile.html', {})

class RegisterView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/register.html', {})

class SearchAmazingView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/search-amazing.html', {})

class SearchView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/search.html', {})

class ShoppingCompleteBuyView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/shopping-complete-buy.html', {})

class ShoppingNoCompleteBuyView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/shopping-no-complete-buy.html', {})

class ShoppingPaymentView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/shopping-payment.html', {})

class ShoppingView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/shopping.html', {})

class WelcomeView(View):
    def get(self, request):
        return render(request, 'topkalaTemplate/welcome.html', {})

topkalaTemplate/templates/topkalaTemplate/base_log_pass.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
    <title>Topkala</title>
    <!--     Fonts and icons     -->

    <link rel="stylesheet" href="{% static 'topkalaTemplate/assets/fonts/font-awesome/css/font-awesome.min.css' %}" />
    <link href="{% static 'topkalaTemplate/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'topkalaTemplate/assets/css/now-ui-kit.css' %}" rel="stylesheet" />
    <link href="{% static 'topkalaTemplate/assets/css/plugins/owl.carousel.css' %}" rel="stylesheet" />
    <link href="{% static 'topkalaTemplate/assets/css/plugins/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'topkalaTemplate/assets/css/main.css' %}" rel="stylesheet" />
</head>

<body>
    <div class="wrapper default">
        {% block content %}
        {% endblock %}

        <footer class="mini-footer">
            <nav>
                <div class="container">
                    <ul class="menu">
                        <li>
                            <a href="#">درباره تاپ کالا</a>
                        </li>
                        <li>
                            <a href="#">فرصت‌های شغلی</a>
                        </li>
                        <li>
                            <a href="#">تماس با ما</a>
                        </li>
                        <li>
                            <a href="#">همکاری با سازمان‌ها</a>
                        </li>

                    </ul>
                </div>
            </nav>
            <div class="copyright-bar">
                <div class="container">
                    <p>
                        استفاده از مطالب فروشگاه اینترنتی تاپ کالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است.
                        کلیه حقوق این سایت متعلق
                        به شرکت نوآوران فن آوازه (فروشگاه آنلاین تاپ کالا) می‌باشد.
                    </p>
                </div>
            </div>
        </footer>
    </div>
</body>
<!--   Core JS Files   -->

<script src="{% static 'topkalaTemplate/assets/js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/bootstrap-switch.js' %}"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/jquery.sharrre.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/now-ui-kit.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/countdown.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/owl.carousel.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/plugins/jquery.easing.1.3.min.js' %}" type="text/javascript"></script>
<script src="{% static 'topkalaTemplate/assets/js/main.js' %}" type="text/javascript"></script>

</html>

-

topkalaTemplate/templates/topkalaTemplate/cart-empty.html


{% extends 'topkalaTemplate/base.html' %}
{% load static %}

{% block content %}
<!-- main -->
<main class="cart default">
    <div class="container text-center">
        <div class="cart-empty">
            <div class="cart-empty-icon">
                <i class="now-ui-icons shopping_basket"></i>
            </div>
            <div class="cart-empty-title">سبد خرید شما خالیست!</div>
            <div class="parent-btn">
                <a href="{% url 'topkalaTemplate:login' %}" class="dk-btn dk-btn-success">
                    به حساب کاربری خود وارد شوید
                    <i class="fa fa-sign-in"></i>
                </a>
            </div>
            <div class="cart-empty-url">
                <span>کاربر جدید هستید؟</span>
                <a href="{% url 'topkalaTemplate:register' %}">ثبت‌نام در تاپ کالا</a>
            </div>
        </div>
    </div>
</main>
<!-- main -->
{% endblock %}

topkalaTemplate/templates/topkalaTemplate/cart.html


{% extends 'topkalaTemplate/base.html' %}
{% load static %}

{% block content %}
<!-- main -->
<main class="cart-page default">
    <div class="container">
        <div class="row">
            <div class="cart-page-content col-xl-9 col-lg-8 col-md-12 order-1">
                <div class="cart-page-title">
                    <h1>سبد خرید</h1>
                </div>
                <div class="table-responsive checkout-content default">
                    <table class="table">
                        <tbody>
                            <tr class="checkout-item">
                                <td>
                                    <img src="assets/img/cart/1335154.jpg" alt="">
                                    <button class="checkout-btn-remove"></button>
                                </td>
                                <td>
                                    <h3 class="checkout-title">
                                        گوشی موبایل اپل مدل iPhone X ظرفیت 256 گیگابایت
                                    </h3>
                                </td>
                                <td>۱ عدد</td>
                                <td>۱۵,۳۹۰,۰۰۰ تومان</td>
                            </tr>
                            <tr class="checkout-item">
                                <td>
                                    <img src="assets/img/cart/1335154.jpg" alt="">
                                    <button class="checkout-btn-remove"></button>
                                </td>
                                <td>
                                    <h3 class="checkout-title">
                                        گوشی موبایل اپل مدل iPhone X ظرفیت 256 گیگابایت
                                    </h3>
                                </td>
                                <td>۱ عدد</td>
                                <td>۱۵,۳۹۰,۰۰۰ تومان</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <aside class="cart-page-aside col-xl-3 col-lg-4 col-md-6 center-section order-2">
                <div class="checkout-aside">
                    <div class="checkout-summary">
                        <div class="checkout-summary-main">
                            <ul class="checkout-summary-summary">
                                <li><span>مبلغ کل (۱ کالا)</span><span>۱۵,۳۹۰,۰۰۰ تومان</span></li>
                                <li>
                                    <span>هزینه ارسال</span>
                                    <span>وابسته به آدرس<span class="wiki wiki-holder"><span
                                                class="wiki-sign"></span>
                                            <div class="wiki-container js-dk-wiki is-right">
                                                <div class="wiki-arrow"></div>
                                                <p class="wiki-text">
                                                    هزینه ارسال مرسولات می‌تواند وابسته به شهر و آدرس گیرنده
                                                    متفاوت باشد. در
                                                    صورتی که هر
                                                    یک از مرسولات حداقل ارزشی برابر با ۱۰۰هزار تومان داشته باشد،
                                                    آن مرسوله
                                                    بصورت رایگان
                                                    ارسال می‌شود.<br>
                                                    "حداقل ارزش هر مرسوله برای ارسال رایگان، می تواند متغیر
                                                    باشد."
                                                </p>
                                            </div>
                                        </span></span>
                                </li>
                            </ul>
                            <div class="checkout-summary-devider">
                                <div></div>
                            </div>
                            <div class="checkout-summary-content">
                                <div class="checkout-summary-price-title">مبلغ قابل پرداخت:</div>
                                <div class="checkout-summary-price-value">
                                    <span class="checkout-summary-price-value-amount">۱۵,۳۹۰,۰۰۰</span>تومان
                                </div>
                                <a href="#" class="selenium-next-step-shipping">
                                    <div class="parent-btn">
                                        <button class="dk-btn dk-btn-info">
                                            ادامه ثبت سفارش
                                            <i class="now-ui-icons shopping_basket"></i>
                                        </button>
                                    </div>
                                </a>
                                <div>
                                    <span>
                                        کالاهای موجود در سبد شما ثبت و رزرو نشده‌اند، برای ثبت سفارش مراحل بعدی
                                        را تکمیل
                                        کنید.
                                    </span>
                                    <span class="wiki wiki-holder"><span class="wiki-sign"></span>
                                        <div class="wiki-container is-right">
                                            <div class="wiki-arrow"></div>
                                            <p class="wiki-text">
                                                محصولات موجود در سبد خرید شما تنها در صورت ثبت و پرداخت سفارش
                                                برای شما رزرو
                                                می‌شوند. در
                                                صورت عدم ثبت سفارش، تاپ کالا هیچگونه مسئولیتی در قبال تغییر
                                                قیمت یا موجودی
                                                این کالاها
                                                ندارد.
                                            </p>
                                        </div>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="checkout-feature-aside">
                        <ul>
                            <li class="checkout-feature-aside-item checkout-feature-aside-item-guarantee">
                                هفت روز
                                ضمانت تعویض
                            </li>
                            <li class="checkout-feature-aside-item checkout-feature-aside-item-cash">
                                پرداخت در محل با
                                کارت بانکی
                            </li>
                            <li class="checkout-feature-aside-item checkout-feature-aside-item-express">
                                تحویل اکسپرس
                            </li>
                        </ul>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</main>
<!-- main -->
{% endblock %}

topkalaTemplate/templates/topkalaTemplate/login.html
{% extends 'topkalaTemplate/base_log_pass.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="main-content col-12 col-md-7 col-lg-5 mx-auto">
            <div class="account-box">
                <a href="#" class="logo">
                    <img src="assets/img/logo.png" alt="">
                </a>
                <div class="account-box-title text-right">ورود به تاپ کالا</div>
                <div class="account-box-content">
                    <form class="form-account">
                        <div class="form-account-title">ایمیل یا شماره موبایل</div>
                        <div class="form-account-row">
                            <label class="input-label"><i class="now-ui-icons users_single-02"></i></label>
                            <input class="input-field" type="text"
                                placeholder="ایمیل یا شماره موبایل خود را وارد نمایید">
                        </div>
                        <div class="form-account-title">رمز عبور
                            <a href="" class="btn-link-border form-account-link">رمز
                                عبور خود را فراموش
                                کرده ام</a>
                        </div>
                        <div class="form-account-row">
                            <label class="input-label"><i
                                    class="now-ui-icons ui-1_lock-circle-open"></i></label>
                            <input class="input-field" type="password"
                                placeholder="رمز عبور خود را وارد نمایید">
                        </div>
                        <div class="form-account-row form-account-submit">
                            <div class="parent-btn">
                                <button class="dk-btn dk-btn-info">
                                    ورود به تاپ کالا
                                    <i class="fa fa-sign-in"></i>
                                </button>
                            </div>
                        </div>
                        <div class="form-account-agree">
                            <label class="checkbox-form checkbox-primary">
                                <input type="checkbox" checked="checked" id="agree">
                                <span class="checkbox-check"></span>
                            </label>
                            <label for="agree">مرا به خاطر داشته باش</label>
                        </div>
                    </form>
                </div>
                <div class="account-box-footer">
                    <span>کاربر جدید هستید؟</span>
                    <a href="#" class="btn-link-border">ثبت‌نام در
                        تاپ کالا</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}